/**
 * @file tpl_external_interrupts.c
 *
 * @section desc File description
 *
 * External interrupts init and acknowledge functions for CortexM4
 * Automatically generated by goil on Www Mmm dd hh:mm:ss yyyy
 * from root OIL file LearnInDepth_SW.oil
 *
 * @section copyright Copyright
 *
 * Trampoline OS
 *
 * Trampoline is copyright (c) IRCCyN 2005-2007
 * Trampoline is protected by the French intellectual property law.
 *
 * This software is distributed under the GNU Public Licence v2
 *
 */

#include "tpl_machine.h"
#include "tpl_cortex_definitions.h"
#include "pinAccess.h"


/*
 * External Interrupts initialization for the STM32F407 Microcontroller
 *
 * Interrupt vectors are EXTI0_IRQ, EXTI1_IRQ, EXTI2_IRQ, EXTI3_IRQ, EXTI4_IRQ
 * EXTI5_9_IRQ and EXTI15_10_IRQ
 *
 * Inits are done according to the source(s) pin(s) selected for an interrupt
 * vector corresponding to an or a set of interrupt(s) line(s)
 */
#define OS_START_SEC_CODE
#include "tpl_memmap.h"

FUNC(void, OS_CODE) tpl_init_external_interrupts()
{
// ---

    /* Program the pins of the GPIO */
    pinMode(GPIOA,0,INPUT);

    /* Set the clock for SYSCFG */
    RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;
    RCC->APB2ENR; /* force read access */

    /* Set Interrupt Mask Register */
    EXTI->IMR |= EXTI_IMR_MR0;

    /* select port associated to each interrupt */
    SYSCFG->EXTICR[0] &= ~SYSCFG_EXTICR1_EXTI0; /*PA0*/
    SYSCFG->EXTICR[0] |=  SYSCFG_EXTICR1_EXTI0_PA; /* isr on PA0 */

    /* select trigger mode - RISING, FALLIN, BOTH */
    EXTI->RTSR |=  EXTI_RTSR_TR0; /* PA0 : RISING */
    EXTI->FTSR &= ~EXTI_FTSR_TR0;

// -------------------------------------------------------------------------------------

  /* Program the NVIC */

    NVIC_SetPriority(EXTI0_IRQn,OS_ISR_PRIO_UNSHIFTED);
    NVIC_EnableIRQ(EXTI0_IRQn);

}

#define OS_STOP_SEC_CODE
#include "tpl_memmap.h"

/* End of file tpl_external_interrupts.c */

