/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_DoorLock_Indication_SWC.h
 * Generated on: Sun Oct 13 23:35:11 AST
 ********************************************************************/

#include "Rte_DoorLock_Indication_SWC.h"	

#ifndef ARUNIT_DOORLOCK_INDICATION_SWC_H
#define ARUNIT_DOORLOCK_INDICATION_SWC_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef false
    #define false (0)
#endif
#ifndef true
    #define true  (!false)
#endif


void ARUnit_Initialize ();

/***************************************/
/******** Delegates API  ***************/
/***************************************/
DECLSPEC_EXPORT void ARUnit_Set_DoorLock_Indication_SWC_RP_CS_LED_Switch_LED_Switch_Delegate(FunctionPtr_DoorLock_Indication_SWC_RP_CS_LED_Switch_LED_Switch );
DECLSPEC_EXPORT void ARUnit_Call_DoorLock_Indication_SWC_RP_CS_LED_Switch_LED_Switch_ReturnCode(Std_ReturnType returnCode);

/***************************************/
/******** Flags API  *******************/
/***************************************/

/***************************************/
/******** Implicit API  ****************/
/***************************************/
DECLSPEC_EXPORT void ARUnit_IWrite_DoorLock_Indication_SWC_DoorLock_Indication_RP_SR_DoorState_DoorState(myunit8 DoorState);
DECLSPEC_EXPORT myunit8 ARUnit_IRead_DoorLock_Indication_SWC_DoorLock_Indication_RP_SR_DoorState_DoorState(void);
DECLSPEC_EXPORT myunit8* ARUnit_IWriteRef_DoorLock_Indication_SWC_DoorLock_Indication_RP_SR_DoorState_DoorState(void);
/***************************************/
/******** Explicit API  ****************/
/***************************************/
/***************************************/
/******** Runnable Calls****************/
/***************************************/

DECLSPEC_EXPORT void ARUnit_Trigger_DoorLock_Indication_SWC_DoorLock_Indication_Runnable(void);

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* ARUNIT_DOORLOCK_INDICATION_SWC_H */
