/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_DoorSensorAbstractionSWC_Type.h
 * Generated on: Sun Oct 13 23:35:11 AST
 ********************************************************************/

#ifndef RTE_DOORSENSORABSTRACTIONSWC_TYPE_H
#define RTE_DOORSENSORABSTRACTIONSWC_TYPE_H


#include "Rte_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/*************************** range types *****************************/

#define myunit8_LowerLimit  (0U)
#define myunit8_UpperLimit (255U)

/************************ enumeration types **************************/



#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_DOORSENSORABSTRACTIONSWC_TYPE_H */
