/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "lcd.h"
#include "keypad.h"
#include "STM32F103C6_GPIO_Driver.h"
#include "STM32F103x6.h"

//For 7-segment display
#define ZERO			0xC0
#define ONE				0xF9
#define TWO				0xA4
#define THREE			0xB0
#define FOUR			0x99
#define FIVE			0x92
#define SIX				0x82
#define SEVEN			0xF8
#define EIGHT			0x80
#define NINE			0x90
#define	DOT				0x80

//APIs
void clock_init(void);
void sevenSeg_init(void);
void _delay(uint32_t time);

int main(void)
{
    /* Loop forever */
    char button[2] = "\0";
    unsigned char i;
	clock_init();
	LCD_INIT();

	//First part
	LCD_WRITE_STRING("Hey there!");
	_delay(100);
	LCD_Clear_Screen();

	//Second part
	sevenSeg_init();
	unsigned char seg [] = {ZERO, ONE, TWO, THREE, FOUR, FIVE,
			SIX, SEVEN, EIGHT, NINE, ZERO};
	unsigned char lcdDisplay [] = {'0', '1', '2', '3', '4', '5',
			'6', '7', '8', '9', '0'};
	for(i = 0; i < 11; i++){
		LCD_WRITE_CHAR(lcdDisplay[i]) ;
		MCAL_GPIO_writePort(GPIOB, seg[i]<<9);
		_delay(100);
	}
	LCD_Clear_Screen();

	//Third part
	KEYPAD_INIT();
	LCD_WRITE_STRING("Keypad is ready:)");
	_delay(100);
	LCD_Clear_Screen();


	while(1){
		button[0] = KEYPAD_GET_CHAR();
		switch(button[0]){
		case ('N'):
							break;
		case ('!'):
							LCD_Clear_Screen();
		break;
		default:
			LCD_WRITE_STRING(button);
		}
	}
}

void clock_init(void){
	//Enable GPIO A clock
	RCC_GPIOA_CLK_EN();
	//Enable GPIO B clock
	RCC_GPIOB_CLK_EN();
}



void sevenSeg_init(void){
	GPIO_pinConfig_t pinConfig;

	//Enabling port B9 as output
	pinConfig.GPIO_pinNumber = GPIO_PIN_9;
	pinConfig.GPIO_mode = GPIO_MODE_OUTPUT_PP;
	pinConfig.GPIO_output_speed = GPIO_SPEED_10M;
	MCAL_GPIO_init(LCD_PORT, &pinConfig);

	//Enabling port B10 as output
	pinConfig.GPIO_pinNumber = GPIO_PIN_10;
	pinConfig.GPIO_mode = GPIO_MODE_OUTPUT_PP;
	pinConfig.GPIO_output_speed = GPIO_SPEED_10M;
	MCAL_GPIO_init(LCD_PORT, &pinConfig);

	//Enabling port B11 as output
	pinConfig.GPIO_pinNumber = GPIO_PIN_11;
	pinConfig.GPIO_mode = GPIO_MODE_OUTPUT_PP;
	pinConfig.GPIO_output_speed = GPIO_SPEED_10M;
	MCAL_GPIO_init(LCD_PORT, &pinConfig);

	//Enabling port B12 as output
	pinConfig.GPIO_pinNumber = GPIO_PIN_12;
	pinConfig.GPIO_mode = GPIO_MODE_OUTPUT_PP;
	pinConfig.GPIO_output_speed = GPIO_SPEED_10M;
	MCAL_GPIO_init(LCD_PORT, &pinConfig);

	//Enabling port B13 as output
	pinConfig.GPIO_pinNumber = GPIO_PIN_13;
	pinConfig.GPIO_mode = GPIO_MODE_OUTPUT_PP;
	pinConfig.GPIO_output_speed = GPIO_SPEED_10M;
	MCAL_GPIO_init(LCD_PORT, &pinConfig);

	//Enabling port B14 as output
	pinConfig.GPIO_pinNumber = GPIO_PIN_14;
	pinConfig.GPIO_mode = GPIO_MODE_OUTPUT_PP;
	pinConfig.GPIO_output_speed = GPIO_SPEED_10M;
	MCAL_GPIO_init(LCD_PORT, &pinConfig);

	//Enabling port B15 as output
	pinConfig.GPIO_pinNumber = GPIO_PIN_15;
	pinConfig.GPIO_mode = GPIO_MODE_OUTPUT_PP;
	pinConfig.GPIO_output_speed = GPIO_SPEED_10M;
	MCAL_GPIO_init(LCD_PORT, &pinConfig);
}

void _delay(uint32_t time){
	uint32_t i,j;
	for(i = 0; i <  time; i++){
		for(j = 0; j <  255; j++);
	}
}
