/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_DoorLock_Indication_SWC_.c
 * Generated on: Sun Oct 13 23:35:11 AST
 ********************************************************************/

#include "string.h"
#include "Rte_DoorLock_Indication_SWC.h"


Rte_DE_myunit8 DoorLock_Indication_RP_SR_DoorState_DoorState;


const Rte_CDS_DoorLock_Indication_SWC Rte_Instance_DoorLock_Indication_SWC = {
&DoorLock_Indication_RP_SR_DoorState_DoorState
};

const Rte_CDS_DoorLock_Indication_SWC * const Rte_Inst_DoorLock_Indication_SWC = &Rte_Instance_DoorLock_Indication_SWC;


Std_ReturnType DoorLock_Indication_SWC_RP_CS_LED_Switch_LED_Switch_Buffer_retcode = RTE_E_OK;

FunctionPtr_DoorLock_Indication_SWC_RP_CS_LED_Switch_LED_Switch Rte_Call_DoorLock_Indication_SWC_RP_CS_LED_Switch_LED_Switch_Delegate = 0;

myunit8 Rte_IRead_DoorLock_Indication_SWC_DoorLock_Indication_RP_SR_DoorState_DoorState (void)
{
	return (Rte_Inst_DoorLock_Indication_SWC)->DoorLock_Indication_RP_SR_DoorState_DoorState->value;
}
Std_ReturnType Rte_Call_DoorLock_Indication_SWC_RP_CS_LED_Switch_LED_Switch (myunit8 LedState)
{
	Std_ReturnType __result = DoorLock_Indication_SWC_RP_CS_LED_Switch_LED_Switch_Buffer_retcode;
	if ( Rte_Call_DoorLock_Indication_SWC_RP_CS_LED_Switch_LED_Switch_Delegate != 0 ) {
		__result = Rte_Call_DoorLock_Indication_SWC_RP_CS_LED_Switch_LED_Switch_Delegate(LedState);
	}
	return __result;
}
