/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_DoorSensorAbstractionSWC_.c
 * Generated on: Sun Oct 13 23:35:11 AST
 ********************************************************************/

#include "string.h"
#include "Rte_DoorSensorAbstractionSWC.h"


Rte_DE_myunit8 ReadDoorSensor_PP_SR_DoorState;


const Rte_CDS_DoorSensorAbstractionSWC Rte_Instance_DoorSensorAbstractionSWC = {
&ReadDoorSensor_PP_SR_DoorState
};

const Rte_CDS_DoorSensorAbstractionSWC * const Rte_Inst_DoorSensorAbstractionSWC = &Rte_Instance_DoorSensorAbstractionSWC;




void Rte_IWrite_DoorSensorAbstractionSWC_ReadDoorSensor_PP_SR_DoorState (myunit8 DoorState)
{
	(Rte_Inst_DoorSensorAbstractionSWC)->ReadDoorSensor_PP_SR_DoorState->value = DoorState;
}
myunit8* Rte_IWriteRef_DoorSensorAbstractionSWC_ReadDoorSensor_PP_SR_DoorState(void)
{
	return &(Rte_Inst_DoorSensorAbstractionSWC)->ReadDoorSensor_PP_SR_DoorState->value;
}
